### ISSUE TITLE
Feature placement crash related to Thorn Blossom

### ISSUE THREAD

**Issue by Naixatloz** [ManaStar/floral_flair#8]
I was exploring some newly generated chunks when I suddenly crashed. Nothing looked obviously wrong to me, but the crash log points to the Thorn Blossom having something to do with it.
[crash-2024-04-05_02.08.36-server.txt](https://github.com/Chalkboard-Mods/floral-flair-forge/files/14891156/crash-2024-04-05_02.08.36-server.txt)

**Comment by Naixatloz** [comment]
Still happening on 1.20.1-2.2.1. Could it be related to the fact that Thorn Blossoms seemingly can't be placed on anything?
[crash-2024-04-25_17.25.02-server.txt](https://github.com/Chalkboard-Mods/floral-flair-forge/files/15123565/crash-2024-04-25_17.25.02-server.txt)

**Comment by MehVahdJukaar** [comment]
https://github.com/Chalkboard-Mods/floral-flair-forge/blob/c2d60e4940a9c01feaec54772034ff5867361f8b/src/main/java/com/chalkboardmods/floral_flair/common/block/ThornBlossomBlock.java#L158C12-L158C19

This method is NOT nullable
